#!/bin/sh

# [Autostart section]
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -solid '#090b08'
xsetroot -cursor_name left_ptr
xrdb .Xresources
xset r rate 250 45

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#74AA00"
bspc config focused_border_color	"#CC4A05"
bspc config presel_feedback_color       "#FBD6B7"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
